# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11g2eKkF8uzVmbE_GdWxGii82kD7UoOiO
"""

from google.colab import files
from openpyxl import Workbook, load_workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font
# import io
import pandas as pd

wb = Workbook()
ws = wb.active

ws['A1'] = 'Hello'

wb.save('test.xlsx')

